### ISSUE TITLE
About the error of the extension "Styles-Editor".

### ISSUE THREAD

**Issue by Kaka3279** [chrisgoringe/Styles-Editor#98]
Extension "Stable diffusion Web-UI"
I installed the "Styles-Editor" extension, but I got the following message while starting the "Stable diffusion Web-UI" extension.
"*** Error loading script: filemanager.py
    Traceback (most recent call last):
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/Styles-Editor/scripts/filemanager.py", line 11, in <module>
        import pyAesCrypt
    ModuleNotFoundError: No module named 'pyAesCrypt'"
I seem to be able to start "Stable diffusion Web-UI". What should I do?

**Comment by chrisgoringe** [comment]
That's odd. pyAesCrypt should be installed automatically. 

I've implemented a quick fix that just disables encryption if the module isn't there. Try updating.

**Comment by Kaka3279** [comment]
Thank you for your response.
However, I still got the following message.

"Civitai Helper: Get Custom Model Folder
Civitai Helper: Load setting from: /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/Stable-Diffusion-Webui-Civitai-Helper/setting.json
Civitai Helper: No setting file, use default
*** Error loading script: filemanager.py
    Traceback (most recent call last):
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/Styles-Editor/scripts/filemanager.py", line 11, in <module>
        import pyAesCrypt
    ModuleNotFoundError: No module named 'pyAesCrypt'

---
Installing pyAesCrypt for Styles Editor"

The extension seems to be working fine.

**Comment by Kaka3279** [comment]
No more errors.
thank you very much.
